version: "3"
services:
  web:
    image: company_http:latest
    container_name: company_api
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./configs/config.json:/app/config.json
      - ./migrations/:/app/migrations/
    networks:
      - go-network

  postgres:
    image: "postgres:latest"
    container_name: company_postgres
    volumes:
      - ./company.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - go-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -p 5432" ]
      interval: 2s
      timeout: 1s
      retries: 5

networks:
  go-network:
