// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "github.com/AlisskaPie/project-xm/pkg/domain"

	mock "github.com/stretchr/testify/mock"
)

// CompanyEventSender is an autogenerated mock type for the CompanyEventSender type
type CompanyEventSender struct {
	mock.Mock
}

// Send provides a mock function with given fields: ctx, event
func (_m *CompanyEventSender) Send(ctx context.Context, event domain.CompanyEvent) error {
	ret := _m.Called(ctx, event)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.CompanyEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewCompanyEventSender interface {
	mock.TestingT
	Cleanup(func())
}

// NewCompanyEventSender creates a new instance of CompanyEventSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCompanyEventSender(t mockConstructorTestingTNewCompanyEventSender) *CompanyEventSender {
	mock := &CompanyEventSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
